// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {push} from '../models';
import {context} from '../models';

export function CloseSession():Promise<void>;

export function GetNotePads():Promise<push.NotePads>;

export function PadPressed(arg1:push.Note):Promise<void>;

export function RTStart():Promise<void>;

export function SendCC(arg1:number,arg2:number):Promise<void>;

export function SendCCNoteOff(arg1:number):Promise<void>;

export function SendCCNoteOn(arg1:number):Promise<void>;

export function SendNoteOff(arg1:number):Promise<void>;

export function SendNoteOn(arg1:number,arg2:number):Promise<void>;

export function SendPitchBend(arg1:number):Promise<void>;

export function SetLiveMode():Promise<void>;

export function SetScaleMode(arg1:push.ScaleMode):Promise<void>;

export function SetUserMode():Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function Stop():Promise<void>;
