// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession() {
  return window['go']['push']['AbletonPush']['CloseSession']();
}

export function GetNotePads() {
  return window['go']['push']['AbletonPush']['GetNotePads']();
}

export function PadPressed(arg1) {
  return window['go']['push']['AbletonPush']['PadPressed'](arg1);
}

export function RTStart() {
  return window['go']['push']['AbletonPush']['RTStart']();
}

export function SendCC(arg1, arg2) {
  return window['go']['push']['AbletonPush']['SendCC'](arg1, arg2);
}

export function SendCCNoteOff(arg1) {
  return window['go']['push']['AbletonPush']['SendCCNoteOff'](arg1);
}

export function SendCCNoteOn(arg1) {
  return window['go']['push']['AbletonPush']['SendCCNoteOn'](arg1);
}

export function SendNoteOff(arg1) {
  return window['go']['push']['AbletonPush']['SendNoteOff'](arg1);
}

export function SendNoteOn(arg1, arg2) {
  return window['go']['push']['AbletonPush']['SendNoteOn'](arg1, arg2);
}

export function SendPitchBend(arg1) {
  return window['go']['push']['AbletonPush']['SendPitchBend'](arg1);
}

export function SetLiveMode() {
  return window['go']['push']['AbletonPush']['SetLiveMode']();
}

export function SetScaleMode(arg1) {
  return window['go']['push']['AbletonPush']['SetScaleMode'](arg1);
}

export function SetUserMode() {
  return window['go']['push']['AbletonPush']['SetUserMode']();
}

export function Shutdown(arg1) {
  return window['go']['push']['AbletonPush']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['push']['AbletonPush']['Startup'](arg1);
}

export function Stop() {
  return window['go']['push']['AbletonPush']['Stop']();
}
